[openapi]
apikey = '<API_KEY>'        # Enter api key for openai
model = 'text-davinci-003'
temperature = 0
max_tokens = 1500
image_num = 1               # Number of images created
image_size = '512x512'      # Image size/res

[openweather]
apikey = '<API_KEY>'        # Enter api key for openweather-api
base_url = "http://api.openweathermap.org/data/2.5/"
units = 'metric'            # or 'imperial'

